logging_config:
  pre_config:
    define_levels:
      - debug
      - info
      - warn
      - error
      - fatal
    format_as: inspect
    root:
      level: warn

  loggers:
    - name: development
      level: all
      additive: false
      trace: true
      appenders:
        - development

    - name: audit
      level: all
      additive: false
      trace: false
      appenders:
        - audit

  appenders:
    - type: File
      name: development
      filename: /home/rgh/dev/rails/pn/log/development.log
      truncate: false
      layout:
        type: Pattern
        pattern: '%d: [%5l] -- %m\n'

    - type: File
      name: audit
      filename: /home/rgh/dev/rails/pn/log/audit.log
      truncate: false
      layout:
        type: Pattern
        pattern: '%d: [%5l] -- %m\n'
