logging_config:
  pre_config:
    define_levels:
      - debug
      - info
      - warn
      - error
      - fatal
    format_as: inspect
    root:
      level: warn

    - name: audit
      level: all
      additive: false
      trace: false
      appenders:
        - audit

    - type: File
      name: audit
      filename: /var/log/smith/smith.log
      truncate: false
      layout:
        type: Pattern
        pattern: '%d: [%5l] -- %m\n'
